using Volo.Abp;

namespace EmployeeManagementSystem.EntityFrameworkCore;

public abstract class EmployeeManagementSystemEntityFrameworkCoreTestBase : EmployeeManagementSystemTestBase<EmployeeManagementSystemEntityFrameworkCoreTestModule>
{

}
