using Xunit;

namespace EmployeeManagementSystem.EntityFrameworkCore;

[CollectionDefinition(EmployeeManagementSystemTestConsts.CollectionDefinitionName)]
public class EmployeeManagementSystemEntityFrameworkCoreCollection : ICollectionFixture<EmployeeManagementSystemEntityFrameworkCoreFixture>
{

}
